{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zjcoming.tools",
    "module": "AndResGuard-core",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "xdo3tmo2ijblbnwakbcvqd23o4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "AndResGuard-core-0.0.1.jar",
          "url": "AndResGuard-core-0.0.1.jar",
          "size": 126505,
          "sha512": "526390ffc93fec3f98e53f7de6893fe88c39e886ddf4f95feb1715bbbf940cc7ee52a47cf800d525969183492d7949a2f46eb5c855868054c85c627fd500f050",
          "sha256": "08a573f9e4ac6c5af8f9b697d3e99a3d3bd520f28196ae79680db89f5d8d1a3f",
          "sha1": "7eaf9cce59a7cddf8002692b2d7d5cc118922863",
          "md5": "a5294249233085d55aef40de4fdf0f2e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "AndResGuard-core-0.0.1.jar",
          "url": "AndResGuard-core-0.0.1.jar",
          "size": 126505,
          "sha512": "526390ffc93fec3f98e53f7de6893fe88c39e886ddf4f95feb1715bbbf940cc7ee52a47cf800d525969183492d7949a2f46eb5c855868054c85c627fd500f050",
          "sha256": "08a573f9e4ac6c5af8f9b697d3e99a3d3bd520f28196ae79680db89f5d8d1a3f",
          "sha1": "7eaf9cce59a7cddf8002692b2d7d5cc118922863",
          "md5": "a5294249233085d55aef40de4fdf0f2e"
        }
      ]
    }
  ]
}
