{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zjcoming.tools",
    "module": "AndResGuard-core",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "rhlj3xcc2rfozbyqx4cp7xuqpu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "AndResGuard-core-0.0.1.jar",
          "url": "AndResGuard-core-0.0.1.jar",
          "size": 134490,
          "sha512": "31ed59ef67a93e521723ca1b4698efb5d3fbf03ef68de1f2b6eeadc938e1a8639aa6cebf0b6e4e271b9656df7ba2c92c17c119a787e74dc2d4b155723e15f542",
          "sha256": "f8ad5c0d9f735a0c2c346569bcd94f2b563a3eac1d33734b46fde2aec824db9e",
          "sha1": "7d103386a12e4a05b6527ac1a4e9ef410a2caea1",
          "md5": "0de4dd8cb24595bd4ecc30c4a287c4c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "AndResGuard-core-0.0.1.jar",
          "url": "AndResGuard-core-0.0.1.jar",
          "size": 134490,
          "sha512": "31ed59ef67a93e521723ca1b4698efb5d3fbf03ef68de1f2b6eeadc938e1a8639aa6cebf0b6e4e271b9656df7ba2c92c17c119a787e74dc2d4b155723e15f542",
          "sha256": "f8ad5c0d9f735a0c2c346569bcd94f2b563a3eac1d33734b46fde2aec824db9e",
          "sha1": "7d103386a12e4a05b6527ac1a4e9ef410a2caea1",
          "md5": "0de4dd8cb24595bd4ecc30c4a287c4c1"
        }
      ]
    }
  ]
}
