{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zjcoming.tools",
    "module": "res-guard-plugin",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "trw2tkdsbzh7lgwvnkxh6del5m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.gradle",
          "module": "osdetector-gradle-plugin",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.zjcoming.tools",
          "module": "AndResGuard-core",
          "version": {
            "requires": "0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "res-guard-plugin-0.0.1.jar",
          "url": "res-guard-plugin-0.0.1.jar",
          "size": 35825,
          "sha512": "0fef733e88e49c4565e6bb210c0528683037fee00e9355a23625a587ab725e912d14fddebc97a38e11383f6ebcfce4b4c362213b3eb886ad7eb751b6b876d48c",
          "sha256": "7905d089e3545aa7b651526a5b11a3a1c6e9a33330ae4427cf3683368978928a",
          "sha1": "79ff032d5858bc527a2a92bebd11c6aba4b3964a",
          "md5": "9809e9e04511d4e4f66054035af30e50"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.gradle",
          "module": "osdetector-gradle-plugin",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.zjcoming.tools",
          "module": "AndResGuard-core",
          "version": {
            "requires": "0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "res-guard-plugin-0.0.1.jar",
          "url": "res-guard-plugin-0.0.1.jar",
          "size": 35825,
          "sha512": "0fef733e88e49c4565e6bb210c0528683037fee00e9355a23625a587ab725e912d14fddebc97a38e11383f6ebcfce4b4c362213b3eb886ad7eb751b6b876d48c",
          "sha256": "7905d089e3545aa7b651526a5b11a3a1c6e9a33330ae4427cf3683368978928a",
          "sha1": "79ff032d5858bc527a2a92bebd11c6aba4b3964a",
          "md5": "9809e9e04511d4e4f66054035af30e50"
        }
      ]
    }
  ]
}
